#!/usr/bin/env python3
"""Turn the original Pandai logo raster into vector shapes.

Reads assets/brand/pandai_logo_source.png (the logo as designed by Team
Terang Bulan) and writes lib/ui/art/logo_shapes.dart plus
tool/pandai_mark.json, which tool/generate_icons.py uses. The circle and the ring
are fitted exactly; leaves, stem and drop are traced from the pixels.

Needs numpy, pillow and opencv-python-headless.
Usage: python3 tool/trace_logo.py
"""

from pathlib import Path

import cv2
import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "assets/brand/pandai_logo_source.png"
OUTPUT = ROOT / "lib/ui/art/logo_shapes.dart"
EMERALD = np.array([30, 154, 112])
DEEP = np.array([64, 122, 88])
WHITE = np.array([255, 255, 255])
SCALE = 8  # Upscale before tracing for sub-pixel accurate outlines.


def unmix(image):
    """Splits each pixel into emerald, deep green and white amounts.

    Solves pixel = white + a * (emerald - white) + b * (deep - white) for a and
    b, which also handles the anti-aliased edges between the colors.
    """
    basis = np.stack([EMERALD - WHITE, DEEP - WHITE], axis=1).astype(float)
    target = (image - WHITE).reshape(-1, 3).T
    amounts = np.linalg.lstsq(basis, target, rcond=None)[0]
    a, b = (np.clip(v, 0, 1).reshape(image.shape[:2]) for v in amounts)
    return a, b


def upscaled_mask(amount):
    big = cv2.resize(amount.astype(np.float32), None, fx=SCALE, fy=SCALE, interpolation=cv2.INTER_CUBIC)
    return (big > 0.5).astype(np.uint8)


def contours(mask):
    found, hierarchy = cv2.findContours(mask, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
    return found, hierarchy[0] if hierarchy is not None else []


def fit_circle(points):
    x, y = points[:, 0].astype(float), points[:, 1].astype(float)
    a = np.column_stack([x, y, np.ones_like(x)])
    b = x**2 + y**2
    c = np.linalg.lstsq(a, b, rcond=None)[0]
    cx, cy = c[0] / 2, c[1] / 2
    return cx, cy, np.sqrt(c[2] + cx**2 + cy**2)


def simplify(contour, epsilon=0.6):
    approx = cv2.approxPolyDP(contour, epsilon * SCALE / 4, True)
    return approx[:, 0, :].astype(float) / SCALE


def main():
    image = np.asarray(Image.open(SOURCE).convert("RGB")).astype(float)
    height = image.shape[0]
    # Only the mark, not the wordmark below it.
    mark_bottom = int(height * 0.74)
    image = image[:mark_bottom]

    emerald_cov, deep_cov = unmix(image)
    emerald = upscaled_mask(emerald_cov)
    deep = upscaled_mask(deep_cov)

    # Circle: the biggest emerald blob.
    em_contours, em_hier = contours(emerald)
    order = sorted(range(len(em_contours)), key=lambda i: -cv2.contourArea(em_contours[i]))
    circle = fit_circle(em_contours[order[0]][:, 0, :] / SCALE)

    # Ring: measured on the top arc, which nothing else touches.
    ys, xs = np.nonzero(deep)
    px, py = xs / SCALE, ys / SCALE
    dist = np.hypot(px - circle[0], py - circle[1])
    top_arc = py < circle[1] - circle[2] * 0.5
    ring_inner = np.percentile(dist[top_arc], 0.5)
    ring_outer = np.percentile(dist[top_arc], 99.5)
    # Gap: where the ring is open at its far left side.
    side = (px < circle[0] - ring_inner) & (dist > ring_inner - 1) & (dist < ring_outer + 1)
    rows = py[side]
    above = rows[rows < circle[1]].max()
    below = rows[rows > circle[1]].min()

    # Leaves: the two big emerald blobs below the circle, with holes.
    leaves = []
    for i in order[1:]:
        c = em_contours[i]
        x, y, w, h = cv2.boundingRect(c)
        if y / SCALE > circle[1] + circle[2] and cv2.contourArea(c) > 200 * SCALE * SCALE:
            holes = [em_contours[j] for j in range(len(em_contours)) if em_hier[j][3] == i]
            leaves.append((c, holes))

    # Stem and drop: deep shapes below the ring.
    deep_contours, deep_hier = contours(deep)
    stems = []
    for i, c in enumerate(deep_contours):
        if deep_hier[i][3] != -1:
            continue
        x, y, w, h = cv2.boundingRect(c)
        if (y + h) / SCALE > circle[1] + ring_outer + 4 and cv2.contourArea(c) > 40 * SCALE * SCALE:
            stems.append(c)

    # Everything is stored relative to a unit square around the mark.
    all_points = np.vstack([c[:, 0, :] for c, _ in leaves] + [c[:, 0, :] for c in stems]) / SCALE
    top = circle[1] - ring_outer
    bottom = all_points[:, 1].max()
    left_edge = min(circle[0] - ring_outer, all_points[:, 0].min())
    right_edge = max(circle[0] + ring_outer, all_points[:, 0].max())
    size = max(bottom - top, right_edge - left_edge)
    ox = (left_edge + right_edge) / 2 - size / 2
    oy = top

    def norm(points):
        return [((x - ox) / size, (y - oy) / size) for x, y in points]

    def dart_points(points):
        return "[" + ", ".join(f"Offset({x:.4f}, {y:.4f})" for x, y in norm(points)) + "]"

    lines = [
        "// Generated by tool/trace_logo.py from assets/brand/pandai_logo_source.png.",
        "// Do not edit by hand.",
        "",
        "import 'dart:ui';",
        "",
        "/// Geometry of the Pandai mark in a unit square (0..1).",
        "abstract final class LogoShapes {",
        f"  static const circleCenter = Offset({(circle[0] - ox) / size:.4f}, {(circle[1] - oy) / size:.4f});",
        f"  static const circleRadius = {circle[2] / size:.4f};",
        f"  static const ringInner = {ring_inner / size:.4f};",
        f"  static const ringOuter = {ring_outer / size:.4f};",
        "",
        "  /// The ring is open between these heights, measured from the centre.",
        f"  static const gapAbove = {(circle[1] - above) / size:.4f};",
        f"  static const gapBelow = {(below - circle[1]) / size:.4f};",
        "",
        "  /// Emerald leaves; each list starts with the outline, then holes.",
        "  static const leaves = <List<List<Offset>>>[",
    ]
    for outline, holes in leaves:
        parts = [dart_points(simplify(outline))] + [dart_points(simplify(h)) for h in holes]
        lines.append("    [" + ", ".join(parts) + "],")
    lines.append("  ];")
    lines.append("")
    lines.append("  /// Deep green stem and drop, with their white cut-outs as holes.")
    lines.append("  static const stems = <List<List<Offset>>>[")
    for i, c in enumerate(deep_contours):
        if not any(c is s for s in stems):
            continue
        holes = [deep_contours[j] for j in range(len(deep_contours)) if deep_hier[j][3] == i]
        parts = [dart_points(simplify(c))] + [dart_points(simplify(h)) for h in holes]
        lines.append("    [" + ", ".join(parts) + "],")
    lines.append("  ];")
    lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n")
    preview = {
        "circle": [(circle[0] - ox) / size, (circle[1] - oy) / size, circle[2] / size],
        "ring": [ring_inner / size, ring_outer / size, (circle[1] - above) / size, (below - circle[1]) / size],
        "leaves": [[norm(simplify(o))] + [norm(simplify(h)) for h in hs] for o, hs in leaves],
        "stems": [
            [norm(simplify(c))]
            + [norm(simplify(deep_contours[j])) for j in range(len(deep_contours)) if deep_hier[j][3] == i]
            for i, c in enumerate(deep_contours)
            if any(c is s for s in stems)
        ],
    }
    import json
    (ROOT / "tool/pandai_mark.json").write_text(json.dumps(preview) + "\n")
    print(f"circle {circle}, ring {ring_inner:.1f}-{ring_outer:.1f}, gap {above:.1f}-{below:.1f}")
    print(f"{len(leaves)} leaves, {len(stems)} stem shapes -> {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
